### ISSUE TITLE
NPM distribution?

### ISSUE THREAD

**Issue by x5engine** [zeckson/vernam-cipher#3]
Hello guys,
any more nodejs example? or even browser use?

why no NPM distribution? it's pretty easy and takes 5mn to do!

Thanks

**Comment by zeckson** [comment]
Hi!
> any more nodejs example? or even browser use?

It's not a library actually. It's an enduser application. Available via browser https://zeckson.github.io/vernam-cipher/ or as Google Chrome plugin

> why no NPM distribution? it's pretty easy and takes 5mn to do!

It's not necessary for this project since it shouldn't be published.

**Comment by x5engine** [comment]
why close this? keep it open!

explanation not clear
